### ISSUE TITLE
Unable to issue certificates from Infisical CA

### ISSUE THREAD

**Issue by paulwilljones** [Infisical/infisical-issuer#2]
I have deployed cert-manager and infisical-issuer and created a `Certificate` referencing the `Issuer`, however, cert-manager is unable to decode the certificate PEM block.

```sh
kubectl apply -f https://raw.githubusercontent.com/Infisical/infisical-issuer/main/build/install.yaml
```

```yaml
apiVersion: infisical-issuer.infisical.com/v1alpha1
kind: Issuer
metadata:
  name: issuer-infisical
  namespace: istio-system
spec:
  url: "https://app.infisical.com"
  caId: "XXXXX"
  authentication:
    universalAuth:
      clientId: "XXXXX"
      secretRef:
        name: issuer-infisical-client-secret
        key: cert-manager-issuer
```

Update: the `.spec.authentication.universalAuth.secretRef.key` needs to be `'clientSecret'` as it is hardcoded in the [issuer](https://github.com/Infisical/infisical-issuer/blob/af1cecd34db02e54661ebed7b33f946d8818da37/internal/issuer/signer/signer.go#L42), so the key in the `Secret` needs to match and can't be anything else (the above `cert-manager-issuer` will cause the issuer to silently fail to retrieve the `clientSecret` and therefore not get an access token)

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-test
  namespace: istio-system
spec:
  dnsNames:
    - infisical.example.com
  commonName: infisical.example.com
  secretName: istio-test-tls
  issuerRef:
    name: issuer-infisical
    group: infisical-issuer.infisical.com
    kind: Issuer
  privateKey:
    algorithm: RSA
    size: 2048
  duration: 48h
  renewBefore: 12h
```

```sh
kubectl describe certificate -n istio-system istio-test
Name:         istio-test
Namespace:    istio-system
Labels:       <none>
Annotations:  <none>
API Version:  cert-manager.io/v1
Kind:         Certificate
Metadata:
  Creation Timestamp:  2025-02-24T11:19:44Z
  Generation:          2
  Resource Version:    48414
  UID:                 856190ba-1901-48aa-8e9c-86fbac71ce4c
Spec:
  Common Name:  infisical.example.com
  Dns Names:
    infisical.example.com
  Duration:  48h
  Issuer Ref:
    Group:  infisical-issuer.infisical.com
    Kind:   Issuer
    Name:   issuer-infisical
  Private Key:
    Algorithm:   RSA
    Size:        2048
  Renew Before:  12h
  Secret Name:   istio-test-tls
Status:
  Conditions:
    Last Transition Time:        2025-02-24T11:19:44Z
    Message:                     Issuing certificate as Secret does not exist
    Observed Generation:         1
    Reason:                      DoesNotExist
    Status:                      True
    Type:                        Issuing
    Last Transition Time:        2025-02-24T11:19:44Z
    Message:                     Issuing certificate as Secret does not exist
    Observed Generation:         2
    Reason:                      DoesNotExist
    Status:                      False
    Type:                        Ready
  Next Private Key Secret Name:  istio-test-mlk5t
Events:
  Type    Reason     Age                From                                       Message
  ----    ------     ----               ----                                       -------
  Normal  Issuing    49m                cert-manager-certificates-trigger          Issuing certificate as Secret does not exist
  Normal  Generated  48m                cert-manager-certificates-key-manager      Stored new private key in temporary Secret resource "istio-test-mlk5t"
  Normal  Requested  19m (x2 over 48m)  cert-manager-certificates-request-manager  Created new CertificateRequest resource "istio-test-1"
```

```sh
kubectl logs -n cert-manager cert-manager-99fb49555-cnb2m
...
E0224 12:04:20.955139       1 controller.go:157] "re-queuing item due to error processing" err="error decoding certificate PEM block" logger="cert-manager.controller"
```

```sh
$ kubectl logs -n infisical-issuer-system infisical-issuer-controller-manager-78bb596c47-pdcm8 manager
{"level":"info","ts":"2025-02-24T12:26:49Z","msg":"CertificateRequest has not been approved yet. Ignoring.","controller":"certificaterequest","controllerGroup":"cert-manager.io","controllerKind":"CertificateRequest","CertificateRequest":{
"name":"istio-test-1","namespace":"istio-system"},"namespace":"istio-system","name":"istio-test-1","reconcileID":"7fc45eb0-572b-413f-9a25-413cfad8aacd"}
{"level":"info","ts":"2025-02-24T12:26:49Z","msg":"Initialising Ready condition","controller":"certificaterequest","controllerGroup":"cert-manager.io","controllerKind":"CertificateRequest","CertificateRequest":{"name":"istio-test-1","name
space":"istio-system"},"namespace":"istio-system","name":"istio-test-1","reconcileID":"324ae51e-bc17-462e-a014-179833f6bcb9"}
{"level":"info","ts":"2025-02-24T12:26:50Z","msg":"Signed","controller":"certificaterequest","controllerGroup":"cert-manager.io","controllerKind":"CertificateRequest","CertificateRequest":{"name":"istio-test-1","namespace":"istio-system"}
,"namespace":"istio-system","name":"istio-test-1","reconcileID":"8e9ed1f4-a8eb-4900-a7f1-4f283d391254","issuer":{"name":"issuer-infisical","namespace":"istio-system"}}
{"level":"info","ts":"2025-02-24T12:26:50Z","msg":"CertificateRequest is Ready. Ignoring.","controller":"certificaterequest","controllerGroup":"cert-manager.io","controllerKind":"CertificateRequest","CertificateRequest":{"name":"istio-tes
t-1","namespace":"istio-system"},"namespace":"istio-system","name":"istio-test-1","reconcileID":"30bcccb1-4612-41c1-9719-fb327c07d873"}
{"level":"info","ts":"2025-02-24T12:27:23Z","msg":"Success","controller":"issuer","controllerGroup":"infisical-issuer.infisical.com","controllerKind":"Issuer","Issuer":{"name":"issuer-infisical","namespace":"istio-system"},"namespace":"is
tio-system","name":"issuer-infisical","reconcileID":"132a1830-e801-449c-b592-6860e560e46c"}
```

The machine identity uses Universal Auth and has the Admin Org and Project Roles.
